## se carga dataset

In [95]:
from pandas import DataFrame
import pandas as pd
from sklearn import datasets


dataset = pd.read_csv('iris.csv')
dataset.head(6)

a    b    c    d        class
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa

## se necesita convertir la última columna a valor número, para eso se utiliza LabelEncoder

In [96]:
from sklearn import preprocessing
lb = preprocessing.LabelEncoder()
lb.fit(dataset['class'])
last_column_numeric = lb.transform(dataset['class'])
last_column_numeric


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## una vez convertido, se elimina la columa de string y se agrega la nueva columna de valores numéricos

In [97]:
dataset.drop(columns='class', inplace=True)
dataset['group'] = last_column_numeric
dataset.head(5)

a    b    c    d  group
0  5.1  3.5  1.4  0.2      0
1  4.9  3.0  1.4  0.2      0
2  4.7  3.2  1.3  0.2      0
3  4.6  3.1  1.5  0.2      0
4  5.0  3.6  1.4  0.2      0

## convertimos a csv el nuevo data frame

In [98]:
dataset.to_csv('iris_numeric.csv')

## agregamos las ventanas para las series de tiempo y calculamos la media de cada columna

In [99]:
from matplotlib import pyplot

dataset_soft = dataset.rolling(window=8, min_periods=1).mean()


## Se define el tamaño de ventana que tendra la serie de tiempos, y se transforma a una colección de datos para el entrenamiento supervisado de la red

In [100]:
import Tools as tls

size = 5

dataset_serialized = tls.series_to_supervised(dataset_soft,size, n_out=1, dropnan = True)
dataset_serialized.head(10)

var1(t-5)  var2(t-5)  var3(t-5)  var4(t-5)  var5(t-5)  var1(t-4)  \
5      5.1000   3.500000   1.400000   0.200000        0.0     5.0000   
6      5.0000   3.250000   1.400000   0.200000        0.0     4.9000   
7      4.9000   3.233333   1.366667   0.200000        0.0     4.8250   
8      4.8250   3.200000   1.400000   0.200000        0.0     4.8600   
9      4.8600   3.280000   1.400000   0.200000        0.0     4.9500   
10     4.9500   3.383333   1.450000   0.233333        0.0     4.9000   
11     4.9000   3.385714   1.442857   0.242857        0.0     4.9125   
12     4.9125   3.387500   1.450000   0.237500        0.0     4.8250   
13     4.8250   3.312500   1.450000   0.237500        0.0     4.8250   
14     4.8250   3.325000   1.462500   0.225000        0.0     4.9125   

    var2(t-4)  var3(t-4)  var4(t-4)  var5(t-4)   ...     var1(t-1)  var2(t-1)  \
5    3.250000   1.400000   0.200000        0.0   ...        4.8600   3.280000   
6    3.233333   1.366667   0.200000        0.0   ...        4.9500   3.383333   
7    3.200000   1.400000   0.200000        0.0   ...        4.9000   3.385714   
8    3.280000   1.400000   0.200000        0.0   ...        4.9125   3.387500   
9    3.383333   1.450000   0.233333        0.0   ...        4.8250   3.312500   
10   3.385714   1.442857   0.242857        0.0   ...        4.8250   3.325000   
11   3.387500   1.450000   0.237500        0.0   ...        4.9125   3.387500   
12   3.312500   1.450000   0.237500        0.0   ...        4.9375   3.425000   
13   3.325000   1.462500   0.225000        0.0   ...        4.9125   3.350000   
14   3.387500   1.487500   0.225000        0.0   ...        4.7750   3.237500   

    var3(t-1)  var4(t-1)  var5(t-1)  var1(t)   var2(t)   var3(t)   var4(t)  \
5    1.400000   0.200000        0.0   4.9500  3.383333  1.450000  0.233333   
6    1.450000   0.233333        0.0   4.9000  3.385714  1.442857  0.242857   
7    1.442857   0.242857        0.0   4.9125  3.387500  1.450000  0.237500   
8    1.450000   0.237500        0.0   4.8250  3.312500  1.450000  0.237500   
9    1.450000   0.237500        0.0   4.8250  3.325000  1.462500  0.225000   
10   1.462500   0.225000        0.0   4.9125  3.387500  1.487500  0.225000   
11   1.487500   0.225000        0.0   4.9375  3.425000  1.500000  0.225000   
12   1.500000   0.225000        0.0   4.9125  3.350000  1.500000  0.212500   
13   1.500000   0.212500        0.0   4.7750  3.237500  1.425000  0.175000   
14   1.425000   0.175000        0.0   4.9250  3.312500  1.400000  0.162500   

    var5(t)  
5       0.0  
6       0.0  
7       0.0  
8       0.0  
9       0.0  
10      0.0  
11      0.0  
12      0.0  
13      0.0  
14      0.0  

[10 rows x 30 columns]

## se normalizan datos entre 0 y 1

In [101]:
from sklearn import preprocessing

datasetnorm = preprocessing.minmax_scale(dataset_serialized, feature_range=(0, 1))
datasetnorm = DataFrame(datasetnorm)
print(datasetnorm)

           0         1         2         3    4         5         6   \
0    0.151163  0.736842  0.013889  0.018987  0.0  0.104651  0.526316   
1    0.104651  0.526316  0.013889  0.018987  0.0  0.058140  0.512281   
2    0.058140  0.512281  0.006481  0.018987  0.0  0.023256  0.484211   
3    0.023256  0.484211  0.013889  0.018987  0.0  0.039535  0.551579   
4    0.039535  0.551579  0.013889  0.018987  0.0  0.081395  0.638596   
5    0.081395  0.638596  0.025000  0.035865  0.0  0.058140  0.640602   
6    0.058140  0.640602  0.023413  0.040687  0.0  0.063953  0.642105   
7    0.063953  0.642105  0.025000  0.037975  0.0  0.023256  0.578947   
8    0.023256  0.578947  0.025000  0.037975  0.0  0.023256  0.589474   
9    0.023256  0.589474  0.027778  0.031646  0.0  0.063953  0.642105   
10   0.063953  0.642105  0.033333  0.031646  0.0  0.075581  0.673684   
11   0.075581  0.673684  0.036111  0.031646  0.0  0.063953  0.610526   
12   0.063953  0.610526  0.036111  0.025316  0.0  0.000000  0.51

## preparamos los datos

In [102]:
import numpy as np
from sklearn.model_selection import train_test_split

zy = datasetnorm.iloc[:, -1:]
zx = datasetnorm.iloc[:, :-1].values

In [103]:
X = np.array(zx, dtype='float64')
y = np.array(zy, dtype='float64')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=20)

X_test_noshape = X_test

print(X_train.shape, y_train.shape) 

(116, 29) (116, 1)


In [104]:
X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))
y_train = y_train.reshape((y_train.shape[0], 1, y_train.shape[1]))
y_test = y_test.reshape((y_test.shape[0], 1, y_test.shape[1]))

print(X_train.shape, y_train.shape) 

(116, 1, 29) (116, 1, 1)


## preparamos el modelo

In [105]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() 
model.add(Dense(8, activation = 'relu', input_shape=(X_train.shape[1], X_train.shape[2]))) # importante declarar correctamente shape
model.add(Dense(20, activation='relu'))
model.add(Dense(1))

model.compile(loss = 'mse', optimizer = 'adam', metrics=['accuracy'])

## etrenamos el algoritmo

In [106]:
history = model.fit(X_train, y_train, epochs=50, batch_size=24, validation_data=(X_test, y_test), verbose=1, shuffle=False)

Train on 116 samples, validate on 29 samples
Epoch 1/50
116/116 [==============================] - 0s 3ms/step - loss: 0.2526 - acc: 0.3103 - val_loss: 0.1781 - val_acc: 0.3103
Epoch 2/50
116/116 [==============================] - 0s 65us/step - loss: 0.1557 - acc: 0.3448 - val_loss: 0.1034 - val_acc: 0.4483
Epoch 3/50
116/116 [==============================] - 0s 83us/step - loss: 0.0861 - acc: 0.5776 - val_loss: 0.0551 - val_acc: 0.5517
Epoch 4/50
116/116 [==============================] - 0s 125us/step - loss: 0.0446 - acc: 0.6207 - val_loss: 0.0302 - val_acc: 0.5517
Epoch 5/50
116/116 [==============================] - 0s 88us/step - loss: 0.0254 - acc: 0.6207 - val_loss: 0.0210 - val_acc: 0.5517
Epoch 6/50
116/116 [==============================] - 0s 103us/step - loss: 0.0198 - acc: 0.6207 - val_loss: 0.0187 - val_acc: 0.5517
Epoch 7/50
116/116 [==============================] - 0s 105us/step - loss: 0.0183 - acc: 0.6207 - val_loss: 0.0169 - val_acc: 0.5517
Epoch 8/50
116/116 [==

## graficamos

In [107]:
pyplot.style.use("ggplot")
pyplot.plot(history.history['mean_squared_error'], label='mse')
pyplot.plot(history.history['val_mean_squared_error'], label='val_mse')
pyplot.xlabel('Epochs')
pyplot.ylabel('Value')
pyplot.legend()
pyplot.show()

KeyError: 'mean_squared_error'

## realizamos prediccion

In [108]:
predictions = model.predict(X_test, 10, verbose=2)
predicted = predictions.transpose(2,0,1).reshape(-1,predictions.shape[1])
predicted

array([[ 5.4440159e-01],
       [ 1.0251695e-02],
       [-2.4532650e-02],
       [ 9.1873777e-01],
       [ 3.6606452e-01],
       [ 4.0880740e-03],
       [ 4.8881516e-01],
       [ 6.2595904e-03],
       [ 9.9226725e-01],
       [ 4.7301400e-01],
       [-1.4331161e-02],
       [ 9.7183073e-01],
       [ 9.4522697e-01],
       [ 5.6370628e-01],
       [-1.9202568e-04],
       [ 6.8291712e-01],
       [ 4.3016204e-01],
       [ 1.0346897e+00],
       [-1.9740542e-02],
       [ 4.9168971e-01],
       [ 5.1458991e-01],
       [ 5.6944805e-01],
       [ 5.8040422e-01],
       [ 5.2571440e-01],
       [-7.2221006e-03],
       [ 5.1655030e-01],
       [ 8.2408916e-03],
       [ 1.0120716e+00],
       [ 9.8513156e-01]], dtype=float32)

## precisión de 55%

In [109]:
model.evaluate(X_test, y_test)

29/29 [==============================] - 0s 151us/step


[0.0012940416345372796, 0.5517241358757019]

In [111]:
y_test = y_test.transpose(2,0,1).reshape(-1,y_test.shape[1])
y_test

array([[0.5   ],
       [0.    ],
       [0.    ],
       [1.    ],
       [0.375 ],
       [0.    ],
       [0.5   ],
       [0.    ],
       [1.    ],
       [0.5   ],
       [0.    ],
       [1.    ],
       [1.    ],
       [0.5   ],
       [0.    ],
       [0.75  ],
       [0.4375],
       [1.    ],
       [0.    ],
       [0.5   ],
       [0.5   ],
       [0.5   ],
       [0.5   ],
       [0.5   ],
       [0.    ],
       [0.5   ],
       [0.    ],
       [1.    ],
       [1.    ]])

In [114]:
p = predicted
p = np.around(p,1)
p = np.absolute(p)
p

array([[0.5],
       [0. ],
       [0. ],
       [0.9],
       [0.4],
       [0. ],
       [0.5],
       [0. ],
       [1. ],
       [0.5],
       [0. ],
       [1. ],
       [0.9],
       [0.6],
       [0. ],
       [0.7],
       [0.4],
       [1. ],
       [0. ],
       [0.5],
       [0.5],
       [0.6],
       [0.6],
       [0.5],
       [0. ],
       [0.5],
       [0. ],
       [1. ],
       [1. ]], dtype=float32)

## precisión 72%

In [119]:
total = len(p)
acert = 0
for a,b in zip(y_test,p):
    if a == b:
        acert += 1

print(acert/total*100)

72.41379310344827
